//! Hook script generation and binary resolution for managed git hooks.

use std::ffi::OsString;
use std::path::{Path, PathBuf};

/// Marker comment written into every hook script managed by this tool.
pub const MARKER: &str = "# do-harness-hook v1";

/// Bash prologue shared by managed hook scripts, ending right after
/// `verify --fail-fast`; the per-sensor `--only` arguments are appended by
/// [`script_body`].
///
/// The binary is resolved at hook runtime, in priority order:
/// `$DO_HARNESS_BIN` when set and executable, then `do-harness` on `PATH`,
/// then `<repo root>/target/release/do-harness`.
const SCRIPT_HEADER: &str = r#"#!/usr/bin/env bash
# do-harness-hook v1
# Generated by `do-harness hook install`. Do not edit; re-run install to update.
set -euo pipefail
ROOT="$(git rev-parse --show-toplevel)"
if [[ -n "${DO_HARNESS_BIN:-}" && -x "$DO_HARNESS_BIN" ]]; then
  BIN="$DO_HARNESS_BIN"
elif command -v do-harness >/dev/null 2>&1; then
  BIN="$(command -v do-harness)"
else
  BIN="$ROOT/target/release/do-harness"
  if [[ ! -x "$BIN" ]]; then
    echo "do-harness: binary not found. Set DO_HARNESS_BIN, add do-harness to PATH, or build with: cargo build --release -p do-harness" >&2
    exit 2
  fi
fi
exec "$BIN" --root "$ROOT" verify --fail-fast"#;

/// Builds a complete hook script body for the given sensor argument string.
#[must_use]
pub fn script_body(only_args: &str) -> String {
    format!("{SCRIPT_HEADER}{only_args}\n")
}

/// Renders the `--only <name>` argument list for the given sensors.
///
/// Returns an empty string for an empty list (full suite). The result starts
/// with a space so it can be appended directly after `verify --fail-fast`.
#[must_use]
pub fn only_args(sensors: &[String]) -> String {
    let mut args = String::new();
    for sensor in sensors {
        args.push_str(" --only ");
        args.push_str(sensor);
    }
    args
}

/// Where the `do-harness` binary resolves from for `hook status`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum BinSource {
    /// `$DO_HARNESS_BIN`, verified executable.
    Env(PathBuf),
    /// Found on `PATH`.
    Path(PathBuf),
    /// The repo-local fallback path.
    Repo(PathBuf),
}

impl BinSource {
    /// Whether the resolved path currently exists on disk.
    #[must_use]
    pub fn present(&self) -> bool {
        match self {
            BinSource::Env(_) | BinSource::Path(_) => true,
            BinSource::Repo(path) => path.is_file(),
        }
    }
}

/// Resolves the `do-harness` binary for `hook status` using the process
/// environment: `$DO_HARNESS_BIN`, then `PATH`, then the repo-local fallback.
#[must_use]
pub fn resolve_binary(repo_root: &Path) -> BinSource {
    resolve_binary_with(
        repo_root,
        std::env::var_os("DO_HARNESS_BIN").map(PathBuf::from),
        std::env::var_os("PATH"),
    )
}

/// Testable resolution core: `env_bin` and `path` stand in for the real
/// environment so lookups are deterministic.
fn resolve_binary_with(
    repo_root: &Path,
    env_bin: Option<PathBuf>,
    path: Option<OsString>,
) -> BinSource {
    if let Some(bin) = env_bin
        && is_executable_file(&bin)
    {
        return BinSource::Env(bin);
    }
    if let Some(found) = search_path(path) {
        return BinSource::Path(found);
    }
    BinSource::Repo(repo_root.join("target/release/do-harness"))
}

/// Searches `PATH` entries for an executable `do-harness`.
fn search_path(path: Option<OsString>) -> Option<PathBuf> {
    let path = path?;
    for dir in std::env::split_paths(&path) {
        let candidate = dir.join("do-harness");
        if is_executable_file(&candidate) {
            return Some(candidate);
        }
    }
    None
}

/// Whether `path` is a file and executable (unix); plain file otherwise.
fn is_executable_file(path: &Path) -> bool {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::metadata(path)
            .is_ok_and(|meta| meta.is_file() && meta.permissions().mode() & 0o111 != 0)
    }
    #[cfg(not(unix))]
    {
        path.is_file()
    }
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used)]

    use super::*;
    use std::ffi::OsString;

    fn fake_repo() -> (tempfile::TempDir, PathBuf) {
        let temp = tempfile::tempdir().unwrap();
        let root = temp.path().to_path_buf();
        (temp, root)
    }

    #[cfg(unix)]
    fn write_exec(path: &Path) {
        use std::os::unix::fs::PermissionsExt;
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(path, "#!/bin/sh\n").unwrap();
        std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o755)).unwrap();
    }

    #[cfg(not(unix))]
    fn write_exec(path: &Path) {
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(path, "stub").unwrap();
    }

    #[test]
    fn resolve_prefers_env_bin() {
        let (temp, root) = fake_repo();
        let bin = temp.path().join("envbin");
        write_exec(&bin);
        let source = resolve_binary_with(&root, Some(bin.clone()), None);
        assert_eq!(source, BinSource::Env(bin));
    }

    #[test]
    fn resolve_falls_back_to_path() {
        let (temp, root) = fake_repo();
        let bin = temp.path().join("bin/do-harness");
        write_exec(&bin);
        let path = OsString::from(format!("{}:/usr/bin", temp.path().join("bin").display()));
        let source = resolve_binary_with(&root, None, Some(path));
        assert_eq!(source, BinSource::Path(bin));
    }

    #[test]
    fn resolve_uses_repo_fallback_when_nowhere() {
        let (_temp, root) = fake_repo();
        let source = resolve_binary_with(&root, None, Some(OsString::from("/nonexistent")));
        assert_eq!(
            source,
            BinSource::Repo(root.join("target/release/do-harness"))
        );
        assert!(!source.present());
    }

    #[test]
    fn repo_source_is_present_when_file_exists() {
        let (temp, root) = fake_repo();
        let bin = root.join("target/release/do-harness");
        std::fs::create_dir_all(bin.parent().unwrap()).unwrap();
        std::fs::write(&bin, "stub").unwrap();
        assert!(BinSource::Repo(bin).present());
        assert!(temp.path().exists());
    }

    #[test]
    fn script_body_contains_runtime_resolution_order() {
        let body = script_body(&only_args(&["fmt".to_owned()]));
        assert!(body.contains("DO_HARNESS_BIN"));
        assert!(body.contains("command -v do-harness"));
        assert!(body.contains("target/release/do-harness"));
        assert!(body.contains("verify --fail-fast --only fmt"));
    }
}
