//! Hook script generation and binary resolution for managed git hooks.

use std::ffi::OsString;
use std::path::{Path, PathBuf};

/// Marker comment written into every hook script managed by this tool.
pub const MARKER: &str = "# do-harness-hook v1";

/// Shebang, marker, and `set -euo pipefail` preamble shared by managed hooks,
/// ending right after the `ROOT` detection; the remaining behavior differs per
/// hook so the prologue and the binary-resolution block are separate.
const PROLOGUE: &str = r#"#!/usr/bin/env bash
# do-harness-hook v1
# Generated by `do-harness hook install`. Do not edit; re-run install to update.
set -euo pipefail
ROOT="$(git rev-parse --show-toplevel)"
"#;

/// Bash block that resolves the `do-harness` binary into `$BIN`, given that
/// `$ROOT` is already set by the [`PROLOGUE`]. Resolution priority: the binary
/// in `$ROOT/target/release/do-harness`.
///
/// The binary is resolved at hook runtime, in priority order:
/// `$DO_HARNESS_BIN` when set and executable, then `do-harness` on `PATH`,
/// then `<repo root>/target/release/do-harness`.
const RESOLVE_BIN: &str = r#"if [[ -n "${DO_HARNESS_BIN:-}" && -x "$DO_HARNESS_BIN" ]]; then
  BIN="$DO_HARNESS_BIN"
elif command -v do-harness >/dev/null 2>&1; then
  BIN="$(command -v do-harness)"
else
  BIN="$ROOT/target/release/do-harness"
  if [[ ! -x "$BIN" ]]; then
    echo "do-harness: binary not found. Set DO_HARNESS_BIN, add do-harness to PATH, or build with: cargo build --release -p do-harness" >&2
    exit 2
  fi
fi
"#;

/// Final `exec` line for the verify-based pre-commit/pre-push hooks; the
/// per-sensor `--only` arguments are appended by [`only_args`].
const EXEC_VERIFY: &str = r#"exec "$BIN" --root "$ROOT" verify --fail-fast --record"#;

/// Builds the pre-commit/pre-push hook body by concatenating the prologue,
/// binary-resolution block, the verify exec line, and the sensor arguments.
fn script_header() -> String {
    format!("{PROLOGUE}{RESOLVE_BIN}{EXEC_VERIFY}")
}

/// Builds a complete hook script body for the given sensor argument string.
#[must_use]
pub fn script_body(only_args: &str) -> String {
    format!("{}{only_args}\n", script_header())
}

/// Builds the `commit-msg` hook body: resolves the binary (shared prologue),
/// locates the repo's commitlint script, and runs it against the prepared
/// message file. It does NOT run a full `verify`; a bad subject exits nonzero
/// so the commit is blocked.
#[must_use]
pub fn commit_msg_body() -> String {
    format!(
        "#!/usr/bin/env bash\n# do-harness-hook v1\n# Generated by `do-harness hook install` (commit-msg). Do not edit; re-run install to update.\nset -euo pipefail\nROOT=\"$(git rev-parse --show-toplevel 2>/dev/null || true)\"\nif [[ -z \"$ROOT\" ]]; then\n  echo \"do-harness commit-msg: not a git repository; skipping.\" >&2\n  exit 0\nfi\n{RESOLVE_BIN}if [[ ! -f \"$ROOT/scripts/check-commitlint.sh\" ]]; then\n  echo \"do-harness commit-msg: check-commitlint.sh not found in $ROOT; skipping.\" >&2\n  exit 0\nfi\nexec bash \"$ROOT/scripts/check-commitlint.sh\" --message \"$1\"\n"
    )
}

/// Renders the `--only <name>` argument list for the given sensors.
///
/// Returns an empty string for an empty list (full suite). The result starts
/// with a space so it can be appended directly after `verify --fail-fast`.
#[must_use]
pub fn only_args(sensors: &[String]) -> String {
    let mut args = String::new();
    for sensor in sensors {
        args.push_str(" --only ");
        args.push_str(sensor);
    }
    args
}

/// Where the `do-harness` binary resolves from for `hook status`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum BinSource {
    /// `$DO_HARNESS_BIN`, verified executable.
    Env(PathBuf),
    /// Found on `PATH`.
    Path(PathBuf),
    /// The repo-local fallback path.
    Repo(PathBuf),
}

impl BinSource {
    /// Whether the resolved path currently exists on disk.
    #[must_use]
    pub fn present(&self) -> bool {
        match self {
            BinSource::Env(_) | BinSource::Path(_) => true,
            BinSource::Repo(path) => path.is_file(),
        }
    }
}

/// Resolves the `do-harness` binary for `hook status` using the process
/// environment: `$DO_HARNESS_BIN`, then `PATH`, then the repo-local fallback.
#[must_use]
pub fn resolve_binary(repo_root: &Path) -> BinSource {
    resolve_binary_with(
        repo_root,
        std::env::var_os("DO_HARNESS_BIN").map(PathBuf::from),
        std::env::var_os("PATH"),
    )
}

/// Testable resolution core: `env_bin` and `path` stand in for the real
/// environment so lookups are deterministic.
fn resolve_binary_with(
    repo_root: &Path,
    env_bin: Option<PathBuf>,
    path: Option<OsString>,
) -> BinSource {
    if let Some(bin) = env_bin
        && is_executable_file(&bin)
    {
        return BinSource::Env(bin);
    }
    if let Some(found) = search_path(path) {
        return BinSource::Path(found);
    }
    BinSource::Repo(repo_root.join("target/release/do-harness"))
}

/// Searches `PATH` entries for an executable `do-harness`.
fn search_path(path: Option<OsString>) -> Option<PathBuf> {
    let path = path?;
    for dir in std::env::split_paths(&path) {
        let candidate = dir.join("do-harness");
        if is_executable_file(&candidate) {
            return Some(candidate);
        }
    }
    None
}

/// Whether `path` is a file and executable (unix); plain file otherwise.
fn is_executable_file(path: &Path) -> bool {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::metadata(path)
            .is_ok_and(|meta| meta.is_file() && meta.permissions().mode() & 0o111 != 0)
    }
    #[cfg(not(unix))]
    {
        path.is_file()
    }
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used)]

    use super::*;
    use std::ffi::OsString;

    /// Absolute path to the repo's commitlint script, reached from the test
    /// crate directory (`crates/do-harness`).
    fn commitlint_script() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../scripts/check-commitlint.sh")
    }

    /// Runs the real commitlint script in `--message` mode against `content`.
    fn lint_message(content: &str) -> bool {
        let msg = tempfile::NamedTempFile::new().unwrap();
        std::fs::write(msg.path(), content).unwrap();
        let status = std::process::Command::new("bash")
            .arg(commitlint_script())
            .args(["--message"])
            .arg(msg.path())
            .status()
            .unwrap();
        status.success()
    }

    #[test]
    fn commitlint_message_mode_accepts_single_word_subject() {
        assert!(lint_message("fix: typo\n"));
        assert!(lint_message("# comment\n# template line\nfix: typo\n"));
    }

    #[test]
    fn commitlint_message_mode_rejects_bad_subjects() {
        assert!(!lint_message("Fix: Typo\n"));
        assert!(!lint_message("fix: Typo\n"));
        assert!(!lint_message("bare non-conventional\n"));
    }

    fn fake_repo() -> (tempfile::TempDir, PathBuf) {
        let temp = tempfile::tempdir().unwrap();
        let root = temp.path().to_path_buf();
        (temp, root)
    }

    #[cfg(unix)]
    fn write_exec(path: &Path) {
        use std::os::unix::fs::PermissionsExt;
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(path, "#!/bin/sh\n").unwrap();
        std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o755)).unwrap();
    }

    #[cfg(not(unix))]
    fn write_exec(path: &Path) {
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(path, "stub").unwrap();
    }

    #[test]
    fn resolve_prefers_env_bin() {
        let (temp, root) = fake_repo();
        let bin = temp.path().join("envbin");
        write_exec(&bin);
        let source = resolve_binary_with(&root, Some(bin.clone()), None);
        assert_eq!(source, BinSource::Env(bin));
    }

    #[test]
    fn resolve_falls_back_to_path() {
        let (temp, root) = fake_repo();
        let bin = temp.path().join("bin/do-harness");
        write_exec(&bin);
        let path = OsString::from(format!("{}:/usr/bin", temp.path().join("bin").display()));
        let source = resolve_binary_with(&root, None, Some(path));
        assert_eq!(source, BinSource::Path(bin));
    }

    #[test]
    fn resolve_uses_repo_fallback_when_nowhere() {
        let (_temp, root) = fake_repo();
        let source = resolve_binary_with(&root, None, Some(OsString::from("/nonexistent")));
        assert_eq!(
            source,
            BinSource::Repo(root.join("target/release/do-harness"))
        );
        assert!(!source.present());
    }

    #[test]
    fn repo_source_is_present_when_file_exists() {
        let (temp, root) = fake_repo();
        let bin = root.join("target/release/do-harness");
        std::fs::create_dir_all(bin.parent().unwrap()).unwrap();
        std::fs::write(&bin, "stub").unwrap();
        assert!(BinSource::Repo(bin).present());
        assert!(temp.path().exists());
    }

    #[test]
    fn script_body_contains_runtime_resolution_order() {
        let body = script_body(&only_args(&["fmt".to_owned()]));
        assert!(body.contains("DO_HARNESS_BIN"));
        assert!(body.contains("command -v do-harness"));
        assert!(body.contains("target/release/do-harness"));
        assert!(body.contains("verify --fail-fast --record --only fmt"));
    }

    #[test]
    fn commit_msg_body_contains_resolution_and_message_arg() {
        let body = commit_msg_body();
        assert!(body.contains(MARKER));
        assert!(body.contains("DO_HARNESS_BIN"));
        assert!(body.contains("command -v do-harness"));
        assert!(body.contains("target/release/do-harness"));
        assert!(body.contains("scripts/check-commitlint.sh"));
        assert!(body.contains("--message \"$1\""));
        assert!(!body.contains("verify --fail-fast"));
    }
}
