//! Hook script generation and binary resolution for managed git hooks.

pub use crate::binary::{BinSource, resolve_binary};

/// Marker comment written into every hook script managed by this tool.
pub const MARKER: &str = "# do-harness-hook v1";

/// Shebang, marker, and `set -euo pipefail` preamble shared by managed hooks,
/// ending right after the `ROOT` detection; the remaining behavior differs per
/// hook so the prologue and the binary-resolution block are separate.
const PROLOGUE: &str = r#"#!/usr/bin/env bash
# do-harness-hook v1
# Generated by `do-harness hook install`. Do not edit; re-run install to update.
set -euo pipefail
ROOT="$(git rev-parse --show-toplevel)"
"#;

/// Bash block that resolves the `do-harness` binary into `$BIN`, given that
/// `$ROOT` is already set by the [`PROLOGUE`].
///
/// The binary is resolved at hook runtime, in priority order:
/// `$DO_HARNESS_BIN` when set and executable, then `do-harness` on `PATH`,
/// then `<repo root>/target/release/do-harness` (also trying the `.exe`
/// suffix so hooks work under Git Bash on Windows).
///
/// Two guards keep a *stale* binary from silently running old policy, which is
/// what a globally `cargo install`ed CLI becomes in a dev checkout:
///
/// * If the repo build exists and is newer than the resolved binary, the repo
///   build wins. `$DO_HARNESS_BIN` is an explicit operator choice, so it is
///   never overridden.
/// * Otherwise a binary older than the workspace sources warns on stderr —
///   emitted after the resolution block so every branch is covered, not just
///   the repo fallback.
const RESOLVE_BIN: &str = r#"if [[ -n "${DO_HARNESS_BIN:-}" && -x "$DO_HARNESS_BIN" ]]; then
  BIN="$DO_HARNESS_BIN"
elif command -v do-harness >/dev/null 2>&1; then
  BIN="$(command -v do-harness)"
else
  BIN="$ROOT/target/release/do-harness"
  if [[ ! -x "$BIN" && -x "$BIN.exe" ]]; then
    BIN="$BIN.exe"
  fi
  if [[ ! -x "$BIN" ]]; then
    echo "do-harness: binary not found. Set DO_HARNESS_BIN, add do-harness to PATH, or build with: cargo build --release -p do-harness" >&2
    exit 2
  fi
fi
REPO_BIN="$ROOT/target/release/do-harness"
[[ -x "$REPO_BIN" ]] || { [[ -x "$REPO_BIN.exe" ]] && REPO_BIN="$REPO_BIN.exe"; }
if [[ -z "${DO_HARNESS_BIN:-}" && -x "$REPO_BIN" && "$REPO_BIN" -nt "$BIN" ]]; then
  BIN="$REPO_BIN"
fi
if [[ -n "$(find "$ROOT/crates" -name '*.rs' -newer "$BIN" -print -quit 2>/dev/null)" ]]; then
  echo "do-harness: warning: $BIN is older than workspace sources; rebuild with: cargo build --release -p do-harness (or set DO_HARNESS_BIN)" >&2
fi
"#;

/// Final `exec` line for the verify-based pre-commit/pre-push hooks; the
/// per-sensor `--only` arguments are appended by [`only_args`].
///
/// The `DO_HARNESS_HOOK` export marks the run as hook-driven: a git hook has
/// no task context, so `verify --record` records its beats in the global
/// namespace there by design and skips the `--task` advisory that targets
/// manual/agent runs (see `verify::warn_unscoped_record`).
const EXEC_VERIFY: &str = r#"export DO_HARNESS_HOOK=1
exec "$BIN" --root "$ROOT" verify --fail-fast --record"#;

/// Builds the pre-commit/pre-push hook body by concatenating the prologue,
/// binary-resolution block, the verify exec line, and the sensor arguments.
fn script_header() -> String {
    format!("{PROLOGUE}{RESOLVE_BIN}{EXEC_VERIFY}")
}

/// Builds a complete hook script body for the given sensor argument string.
#[must_use]
pub fn script_body(only_args: &str) -> String {
    format!("{}{only_args}\n", script_header())
}

/// Builds the `commit-msg` hook body: resolves the binary (shared prologue),
/// locates the repo's commitlint script, and runs it against the prepared
/// message file. It does NOT run a full `verify`; a bad subject exits nonzero
/// so the commit is blocked.
///
/// Fail-closed: a missing git repo or a missing commitlint script exits 2 and
/// blocks the commit. Silently skipping (exit 0) would let an unlinted
/// subject through exactly when the guard is broken, so it is never allowed.
#[must_use]
pub fn commit_msg_body() -> String {
    format!(
        "#!/usr/bin/env bash\n# do-harness-hook v1\n# Generated by `do-harness hook install` (commit-msg). Do not edit; re-run install to update.\nset -euo pipefail\nROOT=\"$(git rev-parse --show-toplevel 2>/dev/null || true)\"\nif [[ -z \"$ROOT\" ]]; then\n  echo \"do-harness commit-msg: not a git repository; blocking commit.\" >&2\n  exit 2\nfi\n{RESOLVE_BIN}if [[ ! -f \"$ROOT/scripts/check-commitlint.sh\" ]]; then\n  echo \"do-harness commit-msg: check-commitlint.sh not found in $ROOT; blocking commit.\" >&2\n  exit 2\nfi\nexec bash \"$ROOT/scripts/check-commitlint.sh\" --message \"$1\"\n"
    )
}

/// Renders the `--only <name>` argument list for the given sensors.
///
/// Returns an empty string for an empty list (full suite). The result starts
/// with a space so it can be appended directly after `verify --fail-fast`.
#[must_use]
pub fn only_args(sensors: &[String]) -> String {
    let mut args = String::new();
    for sensor in sensors {
        args.push_str(" --only ");
        args.push_str(sensor);
    }
    args
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used)]

    use super::*;
    use std::path::{Path, PathBuf};

    /// Absolute path to the repo's commitlint script, reached from the test
    /// crate directory (`crates/do-harness`).
    fn commitlint_script() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../scripts/check-commitlint.sh")
    }

    /// Runs the real commitlint script in `--message` mode against `content`.
    fn lint_message(content: &str) -> bool {
        let msg = tempfile::NamedTempFile::new().unwrap();
        std::fs::write(msg.path(), content).unwrap();
        let status = crate::shell::bash()
            .arg(commitlint_script())
            .args(["--message"])
            .arg(msg.path())
            .status()
            .unwrap();
        status.success()
    }

    #[test]
    fn commitlint_message_mode_accepts_single_word_subject() {
        assert!(lint_message("fix: typo\n"));
        assert!(lint_message("# comment\n# template line\nfix: typo\n"));
    }

    #[test]
    fn commitlint_message_mode_rejects_bad_subjects() {
        assert!(!lint_message("Fix: Typo\n"));
        assert!(!lint_message("fix: Typo\n"));
        assert!(!lint_message("bare non-conventional\n"));
    }

    #[test]
    fn script_body_contains_runtime_resolution_order() {
        let body = script_body(&only_args(&["fmt".to_owned()]));
        assert!(body.contains("DO_HARNESS_BIN"));
        assert!(body.contains("command -v do-harness"));
        assert!(body.contains("target/release/do-harness"));
        assert!(body.contains("verify --fail-fast --record --only fmt"));
    }

    #[test]
    fn script_body_resolves_windows_exe_suffix() {
        // Git Bash on Windows resolves `command -v do-harness` to the `.exe`,
        // but the explicit repo fallback must try the suffix too.
        let body = script_body("");
        assert!(body.contains(r#"BIN="$BIN.exe""#));
    }

    /// The staleness warning must sit outside the resolution branches, so a
    /// stale binary found on `PATH` warns too. Previously the check lived only
    /// in the repo-fallback branch, so a `cargo install`ed binary older than
    /// the sources ran silently and the repo build was ignored.
    #[test]
    fn script_body_warns_about_a_stale_binary_from_any_source() {
        let body = script_body("");
        let warn = body
            .find("older than workspace sources")
            .expect("staleness warning missing");
        let path_branch = body
            .find("command -v do-harness")
            .expect("PATH branch missing");
        let exe_fallback = body
            .find(r#"BIN="$BIN.exe""#)
            .expect("exe fallback missing");
        // It is emitted after the resolution block, not nested inside one arm.
        assert!(
            warn > path_branch && warn > exe_fallback,
            "staleness check must follow the whole resolution block"
        );
        // The closing `fi` of the resolution block precedes the warning, so the
        // warning is not inside any branch.
        let resolution_end = body[..warn].rfind("\nfi\n").expect("resolution `fi`");
        assert!(
            resolution_end < warn,
            "warning must be outside the resolution if/elif/else"
        );
    }

    /// A repo build newer than the resolved binary must win, so a globally
    /// installed stale CLI cannot run old policy in a dev checkout.
    /// `DO_HARNESS_BIN` is an explicit choice and is never overridden.
    #[test]
    fn script_body_prefers_a_fresher_repo_build() {
        let body = script_body("");
        let prefer = body
            .find(r#""$REPO_BIN" -nt "$BIN""#)
            .expect("fresher-repo-build guard missing");
        // Examine the whole `if` statement, which begins before the tested
        // fragment; the DO_HARNESS_BIN condition is part of the same statement.
        let start = body[..prefer].rfind("\nif [[").map_or(0, |n| n + 1);
        let end = body[prefer..]
            .find("\nfi")
            .map_or(body.len(), |n| prefer + n);
        let guard = &body[start..end];
        assert!(
            guard.contains("DO_HARNESS_BIN"),
            "explicit pin must not be overridden: {guard}"
        );
        // And it must sit after the resolution block, before the warning.
        let warn = body.find("older than workspace sources").unwrap();
        assert!(
            prefer < warn,
            "preference applies before the staleness warning"
        );
    }

    #[test]
    fn commit_msg_body_contains_resolution_and_message_arg() {
        let body = commit_msg_body();
        assert!(body.contains(MARKER));
        assert!(body.contains("DO_HARNESS_BIN"));
        assert!(body.contains("command -v do-harness"));
        assert!(body.contains("target/release/do-harness"));
        assert!(body.contains("scripts/check-commitlint.sh"));
        assert!(body.contains("--message \"$1\""));
        assert!(!body.contains("verify --fail-fast"));
    }

    #[test]
    fn commit_msg_body_never_silently_skips() {
        // Fail-closed: no `exit 0` escape hatch may remain in the hook body.
        // A broken guard must block the commit (exit 2), never skip the lint.
        assert!(!commit_msg_body().contains("exit 0"));
    }

    /// Writes the generated hook body plus a dummy message file into `dir`
    /// and executes the hook there, returning the exit code (None = killed).
    ///
    /// Hook-inherited repository variables are removed so the generated
    /// hook's `git rev-parse` resolves the fixture directory, not the caller's
    /// repository.
    fn run_commit_msg_hook(dir: &Path) -> Option<i32> {
        let hook = dir.join("commit-msg");
        std::fs::write(&hook, commit_msg_body()).unwrap();
        let msg = dir.join("COMMIT_EDITMSG");
        std::fs::write(&msg, "fix: typo\n").unwrap();
        let mut command = crate::shell::bash();
        command.arg(&hook).arg(&msg).current_dir(dir);
        for key in [
            "GIT_DIR",
            "GIT_WORK_TREE",
            "GIT_INDEX_FILE",
            "GIT_OBJECT_DIRECTORY",
            "GIT_ALTERNATE_OBJECT_DIRECTORIES",
            "GIT_CEILING_DIRECTORIES",
            "GIT_NAMESPACE",
            "GIT_PREFIX",
        ] {
            command.env_remove(key);
        }
        command.status().unwrap().code()
    }

    #[test]
    fn commit_msg_hook_blocks_commit_outside_git_repo() {
        let temp = tempfile::tempdir().unwrap();
        assert_eq!(run_commit_msg_hook(temp.path()), Some(2));
    }

    #[test]
    fn commit_msg_hook_blocks_commit_without_lint_script() {
        let temp = tempfile::tempdir().unwrap();
        let status = crate::changes::git_command(temp.path())
            .args(["init", "-q"])
            .status()
            .unwrap();
        assert!(status.success());
        assert_eq!(run_commit_msg_hook(temp.path()), Some(2));
    }
}
